---
engines:
  fixme:
    enabled: true
  pmd:
    enabled: true
    channel: "beta"
  checkstyle:
    enabled: "true"
    channel: "beta"
ratings:
  paths:
  - src/main/java/**
  - "**.java"
exclude_paths: []
