theme: jekyll-theme-cayman
show_downloads: true
analytics_enabled: true
gems:
  - jemoji
plugins:
  - jekyll-sitemap
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
